"""Calibrate an SBS stereo camera using the ArUco grid generated by
``gen_arucoGrid_SVG_PNG.py``.

The input directory is expected to contain combined stereo images. By default,
each image is split into equal left and right halves. The script estimates each
camera's intrinsics first, then estimates the left-to-right stereo extrinsics
from markers visible in both halves.

Example
-------
python stereo_calibrate_aruco_grid.py \
    --image-dir HBVCAM_4M2214HD-2-v11_20260811 \
    --output calibration_result_aruco_grid.json \
    --debug-dir aruco_grid_detection_debug
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime
from pathlib import Path

import cv2
import numpy as np

import gen_arucoGrid_SVG_PNG as pattern_config


# python stereo_calibrate_aruco_grid.py --image-dir HBVCAM_4M2214HD-2-v11_20260811 --output calibration_result_HBVCAM_aruco_grid.json --debug-dir aruco_grid_detection_debug


# User-adjustable defaults. Pattern dimensions are read from the generator so
# that calibration remains consistent when the printed pattern is changed.
DEFAULT_IMAGE_DIR = "HBVCAM_4M2214HD-2-v11_20260811"
DEFAULT_OUTPUT_JSON = "calibration_result_HBVCAM_aruco_grid.json"
DEFAULT_LAYOUT = "side-by-side"
DEFAULT_MIN_VIEWS = 8
DEFAULT_MIN_MARKERS = 6
DEFAULT_ALPHA = 0.0
IMAGE_SUFFIXES = {".bmp", ".jpeg", ".jpg", ".png", ".tif", ".tiff"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Estimate stereo intrinsics and extrinsics from images of the "
            "ArUco grid generated by gen_arucoGrid_SVG_PNG.py."
        )
    )
    parser.add_argument(
        "--image-dir",
        type=Path,
        default=Path(DEFAULT_IMAGE_DIR),
        help=f"Directory containing stereo images (default: {DEFAULT_IMAGE_DIR})",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(DEFAULT_OUTPUT_JSON),
        help=f"Output JSON path (default: {DEFAULT_OUTPUT_JSON})",
    )
    parser.add_argument(
        "--layout",
        choices=("side-by-side", "top-bottom"),
        default=DEFAULT_LAYOUT,
        help="How the left and right images are packed (default: side-by-side)",
    )
    parser.add_argument(
        "--swap-cameras",
        action="store_true",
        help="Swap the two image halves before calibration",
    )
    parser.add_argument(
        "--recursive",
        action="store_true",
        help="Also search subdirectories for images",
    )
    parser.add_argument(
        "--debug-dir",
        type=Path,
        help="Optional directory for images showing detected markers",
    )
    parser.add_argument(
        "--min-views",
        type=int,
        default=DEFAULT_MIN_VIEWS,
        help=f"Minimum usable views required (default: {DEFAULT_MIN_VIEWS})",
    )
    parser.add_argument(
        "--min-markers",
        type=int,
        default=DEFAULT_MIN_MARKERS,
        help=(
            "Minimum board markers required in each camera and in their "
            f"intersection (default: {DEFAULT_MIN_MARKERS})"
        ),
    )
    parser.add_argument(
        "--grid-rows",
        type=int,
        default=pattern_config.GRID_ROWS,
        help=f"Pattern marker rows (default: {pattern_config.GRID_ROWS})",
    )
    parser.add_argument(
        "--grid-cols",
        type=int,
        default=pattern_config.GRID_COLS,
        help=f"Pattern marker columns (default: {pattern_config.GRID_COLS})",
    )
    parser.add_argument(
        "--start-id",
        type=int,
        default=pattern_config.GRID_START_ID,
        help=f"First marker ID (default: {pattern_config.GRID_START_ID})",
    )
    parser.add_argument(
        "--marker-size-mm",
        type=float,
        default=pattern_config.GRID_MARKER_SIZE_MM,
        help=(
            "Printed black marker edge length in millimetres "
            f"(default: {pattern_config.GRID_MARKER_SIZE_MM})"
        ),
    )
    parser.add_argument(
        "--marker-gap-mm",
        type=float,
        default=pattern_config.GRID_GAP_MM,
        help=(
            "White gap between neighbouring markers in millimetres "
            f"(default: {pattern_config.GRID_GAP_MM})"
        ),
    )
    parser.add_argument(
        "--alpha",
        type=float,
        default=DEFAULT_ALPHA,
        help="Stereo rectification free scaling in [0, 1] (default: 0)",
    )
    args = parser.parse_args()

    if args.min_views < 3:
        parser.error("--min-views must be at least 3")
    if args.min_markers < 1:
        parser.error("--min-markers must be at least 1")
    if args.grid_rows < 1 or args.grid_cols < 1:
        parser.error("--grid-rows and --grid-cols must be positive")
    if args.start_id < 0:
        parser.error("--start-id cannot be negative")
    if args.marker_size_mm <= 0 or args.marker_gap_mm < 0:
        parser.error("Marker size must be positive and marker gap cannot be negative")
    if not 0.0 <= args.alpha <= 1.0:
        parser.error("--alpha must be between 0 and 1")
    return args


def find_image_paths(image_dir: Path, recursive: bool) -> list[Path]:
    candidates = image_dir.rglob("*") if recursive else image_dir.iterdir()
    return sorted(
        path
        for path in candidates
        if path.is_file() and path.suffix.lower() in IMAGE_SUFFIXES
    )


def dictionary_name(dictionary_id: int) -> str:
    for name in dir(cv2.aruco):
        if name.startswith("DICT_") and getattr(cv2.aruco, name) == dictionary_id:
            return name
    return str(dictionary_id)


def create_detector(dictionary_id: int):
    dictionary = cv2.aruco.getPredefinedDictionary(dictionary_id)
    if hasattr(cv2.aruco, "DetectorParameters"):
        parameters = cv2.aruco.DetectorParameters()
    else:
        parameters = cv2.aruco.DetectorParameters_create()

    if hasattr(cv2.aruco, "CORNER_REFINE_SUBPIX"):
        parameters.cornerRefinementMethod = cv2.aruco.CORNER_REFINE_SUBPIX

    if hasattr(cv2.aruco, "ArucoDetector"):
        return cv2.aruco.ArucoDetector(dictionary, parameters), dictionary, parameters
    return None, dictionary, parameters


def detect_markers(gray, detector, dictionary, parameters) -> dict[int, np.ndarray]:
    if detector is not None:
        corners, ids, _ = detector.detectMarkers(gray)
    else:
        corners, ids, _ = cv2.aruco.detectMarkers(
            gray,
            dictionary,
            parameters=parameters,
        )

    if ids is None:
        return {}

    detections: dict[int, np.ndarray] = {}
    for marker_corners, marker_id in zip(corners, ids.flatten()):
        detections[int(marker_id)] = np.asarray(
            marker_corners,
            dtype=np.float32,
        ).reshape(4, 2)
    return detections


def make_board_points(
    rows: int,
    cols: int,
    start_id: int,
    marker_size_mm: float,
    marker_gap_mm: float,
) -> dict[int, np.ndarray]:
    """Return TL, TR, BR, BL 3-D corners for every marker."""
    marker_points: dict[int, np.ndarray] = {}
    pitch = marker_size_mm + marker_gap_mm
    for row in range(rows):
        for col in range(cols):
            marker_id = start_id + row * cols + col
            x = col * pitch
            y = row * pitch
            marker_points[marker_id] = np.array(
                [
                    [x, y, 0.0],
                    [x + marker_size_mm, y, 0.0],
                    [x + marker_size_mm, y + marker_size_mm, 0.0],
                    [x, y + marker_size_mm, 0.0],
                ],
                dtype=np.float32,
            )
    return marker_points


def split_stereo_image(
    image: np.ndarray,
    layout: str,
    swap_cameras: bool,
) -> tuple[np.ndarray, np.ndarray]:
    height, width = image.shape[:2]
    if layout == "side-by-side":
        if width % 2:
            raise ValueError(f"side-by-side image width must be even, got {width}")
        split = width // 2
        left, right = image[:, :split], image[:, split:]
    else:
        if height % 2:
            raise ValueError(f"top-bottom image height must be even, got {height}")
        split = height // 2
        left, right = image[:split, :], image[split:, :]

    if swap_cameras:
        left, right = right, left
    return left, right


def select_board_detections(
    detections: dict[int, np.ndarray],
    board_points: dict[int, np.ndarray],
) -> dict[int, np.ndarray]:
    return {
        marker_id: corners
        for marker_id, corners in detections.items()
        if marker_id in board_points
    }


def collect_points(
    detections: dict[int, np.ndarray],
    marker_ids: list[int],
    board_points: dict[int, np.ndarray],
) -> tuple[np.ndarray, np.ndarray]:
    object_points = np.concatenate(
        [board_points[marker_id] for marker_id in marker_ids],
        axis=0,
    ).astype(np.float32)
    image_points = np.concatenate(
        [detections[marker_id] for marker_id in marker_ids],
        axis=0,
    ).astype(np.float32)
    return object_points, image_points


def draw_detections(
    image: np.ndarray,
    detections: dict[int, np.ndarray],
    label: str,
) -> np.ndarray:
    display = image.copy()
    marker_ids = sorted(detections)
    if marker_ids:
        corners = [detections[marker_id].reshape(1, 4, 2) for marker_id in marker_ids]
        ids = np.asarray(marker_ids, dtype=np.int32).reshape(-1, 1)
        cv2.aruco.drawDetectedMarkers(display, corners, ids)
    cv2.putText(
        display,
        f"{label}: {len(marker_ids)} board markers",
        (20, 40),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.9,
        (0, 255, 255),
        2,
        cv2.LINE_AA,
    )
    return display


def save_debug_image(
    debug_dir: Path,
    relative_name: str,
    left: np.ndarray,
    right: np.ndarray,
    left_detections: dict[int, np.ndarray],
    right_detections: dict[int, np.ndarray],
) -> None:
    left_display = draw_detections(left, left_detections, "L")
    right_display = draw_detections(right, right_detections, "R")
    combined = cv2.hconcat([left_display, right_display])
    safe_name = relative_name.replace("/", "__").replace("\\", "__")
    output_path = debug_dir / f"{Path(safe_name).stem}_detected.jpg"
    cv2.imwrite(str(output_path), combined, [cv2.IMWRITE_JPEG_QUALITY, 92])


def per_view_reprojection_rms(
    object_points: list[np.ndarray],
    image_points: list[np.ndarray],
    rvecs,
    tvecs,
    camera_matrix: np.ndarray,
    distortion: np.ndarray,
) -> list[float]:
    errors: list[float] = []
    for object_view, image_view, rvec, tvec in zip(
        object_points,
        image_points,
        rvecs,
        tvecs,
    ):
        projected, _ = cv2.projectPoints(
            object_view,
            rvec,
            tvec,
            camera_matrix,
            distortion,
        )
        residual = image_view.reshape(-1, 2) - projected.reshape(-1, 2)
        errors.append(float(np.sqrt(np.mean(np.sum(residual * residual, axis=1)))))
    return errors


def symmetric_epipolar_error(
    left_points: np.ndarray,
    right_points: np.ndarray,
    fundamental: np.ndarray,
    left_matrix: np.ndarray,
    left_distortion: np.ndarray,
    right_matrix: np.ndarray,
    right_distortion: np.ndarray,
) -> float:
    # F describes the ideal pinhole cameras, so remove lens distortion while
    # retaining pixel coordinates before measuring point-to-epipolar-line error.
    def undistort(points, matrix, distortion):
        if hasattr(cv2, "undistortPointsIter"):
            criteria = (
                cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_MAX_ITER,
                50,
                1e-12,
            )
            return cv2.undistortPointsIter(
                points.reshape(-1, 1, 2),
                matrix,
                distortion,
                None,
                matrix,
                criteria,
            )
        return cv2.undistortPoints(
            points.reshape(-1, 1, 2),
            matrix,
            distortion,
            P=matrix,
        )

    left = undistort(left_points, left_matrix, left_distortion)
    right = undistort(right_points, right_matrix, right_distortion)
    right_lines = cv2.computeCorrespondEpilines(left, 1, fundamental).reshape(-1, 3)
    left_lines = cv2.computeCorrespondEpilines(right, 2, fundamental).reshape(-1, 3)

    def distances(points: np.ndarray, lines: np.ndarray) -> np.ndarray:
        points_2d = points.reshape(-1, 2)
        numerator = np.abs(
            lines[:, 0] * points_2d[:, 0]
            + lines[:, 1] * points_2d[:, 1]
            + lines[:, 2]
        )
        denominator = np.hypot(lines[:, 0], lines[:, 1])
        return numerator / np.maximum(denominator, np.finfo(np.float64).eps)

    return float(
        0.5
        * (
            np.mean(distances(right_points, right_lines))
            + np.mean(distances(left_points, left_lines))
        )
    )


def int_roi(roi) -> list[int]:
    return [int(value) for value in roi]


def main() -> int:
    args = parse_args()
    image_dir = args.image_dir.expanduser().resolve()
    output_path = args.output.expanduser().resolve()
    debug_dir = args.debug_dir.expanduser().resolve() if args.debug_dir else None

    if not hasattr(cv2, "aruco"):
        print("[ERROR] This OpenCV installation does not include the aruco module.")
        return 1
    if not image_dir.is_dir():
        print(f"[ERROR] Image directory does not exist: {image_dir}")
        return 1

    image_paths = find_image_paths(image_dir, args.recursive)
    if not image_paths:
        print(f"[ERROR] No supported images found in: {image_dir}")
        return 1

    dictionary_id = pattern_config.ARUCO_DICT
    dictionary = cv2.aruco.getPredefinedDictionary(dictionary_id)
    last_marker_id = args.start_id + args.grid_rows * args.grid_cols - 1
    dictionary_capacity = int(dictionary.bytesList.shape[0])
    if last_marker_id >= dictionary_capacity:
        print(
            f"[ERROR] Pattern IDs {args.start_id}-{last_marker_id} exceed "
            f"dictionary capacity 0-{dictionary_capacity - 1}."
        )
        return 1

    board_points = make_board_points(
        args.grid_rows,
        args.grid_cols,
        args.start_id,
        args.marker_size_mm,
        args.marker_gap_mm,
    )
    detector, dictionary, detector_parameters = create_detector(dictionary_id)

    if debug_dir is not None:
        debug_dir.mkdir(parents=True, exist_ok=True)

    left_object_views: list[np.ndarray] = []
    left_image_views: list[np.ndarray] = []
    left_view_names: list[str] = []
    right_object_views: list[np.ndarray] = []
    right_image_views: list[np.ndarray] = []
    right_view_names: list[str] = []
    stereo_object_views: list[np.ndarray] = []
    stereo_left_views: list[np.ndarray] = []
    stereo_right_views: list[np.ndarray] = []
    stereo_view_names: list[str] = []
    stereo_marker_counts: list[int] = []
    image_records: list[dict[str, object]] = []
    image_size: tuple[int, int] | None = None

    print(
        f"Pattern: {dictionary_name(dictionary_id)}, {args.grid_rows}x{args.grid_cols}, "
        f"IDs {args.start_id}-{last_marker_id}, marker={args.marker_size_mm:g} mm, "
        f"gap={args.marker_gap_mm:g} mm"
    )
    print(f"Found {len(image_paths)} image(s) in {image_dir}")

    for index, image_path in enumerate(image_paths, start=1):
        relative_name = str(image_path.relative_to(image_dir))
        record: dict[str, object] = {"image": relative_name}
        image = cv2.imread(str(image_path), cv2.IMREAD_COLOR)
        if image is None:
            record["status"] = "read_failed"
            image_records.append(record)
            print(f"[{index}/{len(image_paths)}] read failed: {relative_name}")
            continue

        try:
            left, right = split_stereo_image(image, args.layout, args.swap_cameras)
        except ValueError as error:
            record["status"] = "invalid_stereo_shape"
            record["reason"] = str(error)
            image_records.append(record)
            print(f"[{index}/{len(image_paths)}] rejected: {relative_name} ({error})")
            continue

        current_size = (left.shape[1], left.shape[0])
        if right.shape[:2] != left.shape[:2]:
            record["status"] = "left_right_size_mismatch"
            image_records.append(record)
            print(f"[{index}/{len(image_paths)}] unequal halves: {relative_name}")
            continue
        if image_size is None:
            image_size = current_size
        elif current_size != image_size:
            record["status"] = "image_size_mismatch"
            record["size"] = [current_size[0], current_size[1]]
            image_records.append(record)
            print(
                f"[{index}/{len(image_paths)}] size mismatch: {relative_name} "
                f"({current_size[0]}x{current_size[1]})"
            )
            continue

        left_all = detect_markers(
            cv2.cvtColor(left, cv2.COLOR_BGR2GRAY),
            detector,
            dictionary,
            detector_parameters,
        )
        right_all = detect_markers(
            cv2.cvtColor(right, cv2.COLOR_BGR2GRAY),
            detector,
            dictionary,
            detector_parameters,
        )
        left_detections = select_board_detections(left_all, board_points)
        right_detections = select_board_detections(right_all, board_points)
        left_ids = sorted(left_detections)
        right_ids = sorted(right_detections)
        common_ids = sorted(set(left_ids).intersection(right_ids))

        if len(left_ids) >= args.min_markers:
            object_view, image_view = collect_points(
                left_detections,
                left_ids,
                board_points,
            )
            left_object_views.append(object_view)
            left_image_views.append(image_view)
            left_view_names.append(relative_name)
        if len(right_ids) >= args.min_markers:
            object_view, image_view = collect_points(
                right_detections,
                right_ids,
                board_points,
            )
            right_object_views.append(object_view)
            right_image_views.append(image_view)
            right_view_names.append(relative_name)
        if len(common_ids) >= args.min_markers:
            object_view, left_view = collect_points(
                left_detections,
                common_ids,
                board_points,
            )
            _, right_view = collect_points(
                right_detections,
                common_ids,
                board_points,
            )
            stereo_object_views.append(object_view)
            stereo_left_views.append(left_view)
            stereo_right_views.append(right_view)
            stereo_view_names.append(relative_name)
            stereo_marker_counts.append(len(common_ids))

        stereo_usable = len(common_ids) >= args.min_markers
        record.update(
            {
                "status": "stereo_usable" if stereo_usable else "insufficient_common_markers",
                "left_board_markers": len(left_ids),
                "right_board_markers": len(right_ids),
                "common_board_markers": len(common_ids),
            }
        )
        image_records.append(record)
        print(
            f"[{index}/{len(image_paths)}] {relative_name}: "
            f"L={len(left_ids)}, R={len(right_ids)}, common={len(common_ids)} "
            f"({'use' if stereo_usable else 'skip'})"
        )

        if debug_dir is not None:
            save_debug_image(
                debug_dir,
                relative_name,
                left,
                right,
                left_detections,
                right_detections,
            )

    counts = {
        "left": len(left_object_views),
        "right": len(right_object_views),
        "stereo": len(stereo_object_views),
    }
    insufficient = [name for name, count in counts.items() if count < args.min_views]
    if insufficient or image_size is None:
        print(
            f"[ERROR] Not enough usable views (required {args.min_views}): "
            f"left={counts['left']}, right={counts['right']}, stereo={counts['stereo']}"
        )
        print(
            "Capture the flat grid at varied positions, distances, and tilts while "
            "keeping enough markers visible in both cameras."
        )
        return 1

    print("Calibrating left camera intrinsics...")
    try:
        (
            left_rms,
            left_matrix,
            left_distortion,
            left_rvecs,
            left_tvecs,
        ) = cv2.calibrateCamera(
            left_object_views,
            left_image_views,
            image_size,
            None,
            None,
        )
        print("Calibrating right camera intrinsics...")
        (
            right_rms,
            right_matrix,
            right_distortion,
            right_rvecs,
            right_tvecs,
        ) = cv2.calibrateCamera(
            right_object_views,
            right_image_views,
            image_size,
            None,
            None,
        )

        print("Calibrating left-to-right stereo extrinsics...")
        stereo_criteria = (
            cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_MAX_ITER,
            100,
            1e-7,
        )
        (
            stereo_rms,
            left_matrix,
            left_distortion,
            right_matrix,
            right_distortion,
            rotation,
            translation,
            essential,
            fundamental,
        ) = cv2.stereoCalibrate(
            stereo_object_views,
            stereo_left_views,
            stereo_right_views,
            left_matrix,
            left_distortion,
            right_matrix,
            right_distortion,
            image_size,
            criteria=stereo_criteria,
            flags=cv2.CALIB_FIX_INTRINSIC,
        )
        (
            rectify_left,
            rectify_right,
            projection_left,
            projection_right,
            disparity_to_depth,
            valid_roi_left,
            valid_roi_right,
        ) = cv2.stereoRectify(
            left_matrix,
            left_distortion,
            right_matrix,
            right_distortion,
            image_size,
            rotation,
            translation,
            alpha=args.alpha,
        )
    except cv2.error as error:
        print(f"[ERROR] OpenCV calibration failed:\n{error}")
        return 1

    left_view_rms = per_view_reprojection_rms(
        left_object_views,
        left_image_views,
        left_rvecs,
        left_tvecs,
        left_matrix,
        left_distortion,
    )
    right_view_rms = per_view_reprojection_rms(
        right_object_views,
        right_image_views,
        right_rvecs,
        right_tvecs,
        right_matrix,
        right_distortion,
    )
    epipolar_errors = [
        symmetric_epipolar_error(
            left,
            right,
            fundamental,
            left_matrix,
            left_distortion,
            right_matrix,
            right_distortion,
        )
        for left, right in zip(stereo_left_views, stereo_right_views)
    ]
    baseline_mm = float(np.linalg.norm(translation))

    result = {
        "schema_version": 1,
        "calibration_type": "stereo_pinhole_aruco_grid",
        "calibration_time": datetime.now().astimezone().isoformat(timespec="seconds"),
        "image_size_per_camera": {
            "width": image_size[0],
            "height": image_size[1],
        },
        "reprojection_error": float(stereo_rms),
        "intrinsic_L": {
            "rms_reprojection_error_px": float(left_rms),
            "matrix": left_matrix.tolist(),
            "distortion": left_distortion.reshape(-1).tolist(),
            "per_view_rms_px": [
                {"image": name, "rms": error}
                for name, error in zip(left_view_names, left_view_rms)
            ],
        },
        "intrinsic_R": {
            "rms_reprojection_error_px": float(right_rms),
            "matrix": right_matrix.tolist(),
            "distortion": right_distortion.reshape(-1).tolist(),
            "per_view_rms_px": [
                {"image": name, "rms": error}
                for name, error in zip(right_view_names, right_view_rms)
            ],
        },
        "extrinsic": {
            "convention": "X_right = R * X_left + T",
            "units": "millimetres",
            "stereo_rms_reprojection_error_px": float(stereo_rms),
            "mean_symmetric_epipolar_error_undistorted_px": float(
                np.mean(epipolar_errors)
            ),
            "baseline_mm": baseline_mm,
            "R": rotation.tolist(),
            "T": translation.reshape(-1).tolist(),
            "E": essential.tolist(),
            "F": fundamental.tolist(),
            "per_view_epipolar_error_undistorted_px": [
                {
                    "image": name,
                    "common_markers": marker_count,
                    "mean_symmetric_error": error,
                }
                for name, marker_count, error in zip(
                    stereo_view_names,
                    stereo_marker_counts,
                    epipolar_errors,
                )
            ],
        },
        "rectification": {
            "alpha": args.alpha,
            "R1": rectify_left.tolist(),
            "R2": rectify_right.tolist(),
            "P1": projection_left.tolist(),
            "P2": projection_right.tolist(),
            "Q": disparity_to_depth.tolist(),
            "valid_roi_L": int_roi(valid_roi_left),
            "valid_roi_R": int_roi(valid_roi_right),
        },
        "pattern": {
            "source": "gen_arucoGrid_SVG_PNG.py",
            "dictionary": dictionary_name(dictionary_id),
            "rows": args.grid_rows,
            "columns": args.grid_cols,
            "start_id": args.start_id,
            "end_id": last_marker_id,
            "marker_size_mm": args.marker_size_mm,
            "marker_gap_mm": args.marker_gap_mm,
            "id_order": "row-major, left-to-right, top-to-bottom",
        },
        "dataset": {
            "image_directory": str(image_dir),
            "layout": args.layout,
            "swap_cameras": args.swap_cameras,
            "minimum_markers": args.min_markers,
            "minimum_views": args.min_views,
            "usable_left_views": len(left_object_views),
            "usable_right_views": len(right_object_views),
            "usable_stereo_views": len(stereo_object_views),
            "images": image_records,
        },
    }

    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with output_path.open("w", encoding="utf-8") as output_file:
            json.dump(result, output_file, indent=2, ensure_ascii=False)
    except OSError as error:
        print(f"[ERROR] Could not write calibration JSON: {output_path}\n{error}")
        return 1

    print("Calibration complete.")
    print(f"Left intrinsic RMS : {left_rms:.4f} px")
    print(f"Right intrinsic RMS: {right_rms:.4f} px")
    print(f"Stereo RMS         : {stereo_rms:.4f} px")
    print(
        "Mean epipolar error: "
        f"{np.mean(epipolar_errors):.4f} undistorted px"
    )
    print(f"Baseline           : {baseline_mm:.4f} mm")
    print(f"Saved JSON         : {output_path}")
    if debug_dir is not None:
        print(f"Detection images   : {debug_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
